### ISSUE TITLE
Feature Request: Compound graphs

### ISSUE THREAD

**Issue by nileshtrivedi** [micrology/prsm#105]
Compound graphs allow nodes to be children of or included in other nodes. In other words, they have two kind of edges: adjacency and inclusion. Here is an [example of a compound graph](https://foresight.org/ext/ForesightTechTree/)

The "Theory of Change" map linked on the website hints at such a graph but I could not find a way to add/remove child/parent relationships among nodes.

![image](https://user-images.githubusercontent.com/19304/184532843-98e37649-6c6c-494f-8860-e04dd4813e53.png)

**Comment by nileshtrivedi** [comment]
BTW, I am the developer of the compound graph editor tool that I linked above. [This tool is open-source as well](https://codeberg.org/nilesh/grapher). I now wish I had come across PRSM before I started developing my own. 😄

**Comment by micrology** [comment]
Hi,  Thanks for getting in touch! 

PRSM does implement clustering, which is not quite the same as what you have in mind, but may be useful.  See https://prsm.uk/help.html#analysis-tab and the sub-section: : "Cluster".

And thanks for the (indirect) link to cytoscape - curiously, I had not come across this before.

**Comment by nileshtrivedi** [comment]
Thanks. Clustering is definitely useful. I'm wondering though: What would it take to support parent child nodes - at least for 3 or 4 levels of hierarchy? Can you suggest a plan of action if I were to take a stab at this?
