### ISSUE TITLE
Incorrect factor node moved when previous factor is selected

### ISSUE THREAD

**Issue by serialc** [micrology/prsm#94]
Hard to make clear in the title.
Sorry Wayland is causing problems recording a screen cast.

To reproduce:
Create two nodes as in image below:
![expected](https://user-images.githubusercontent.com/777410/133939878-fb704d6a-0a25-43ab-b568-b0fbb604547b.png)

Select the right factor (2):
![problem](https://user-images.githubusercontent.com/777410/133939879-6cbcd1f6-8554-485b-b610-8e3b8f812f66.png)

Move the left factor (1).
Move the right factor (2).

In the last step factor 1 will move, not factor 2 as expected.

**Comment by micrology** [comment]
I can reproduce this, but for the moment I have no clue about why it is happening.

**Comment by micrology** [comment]
PRSM 1.9.3 (available at https://prsm.uk/prsm.html) no longer has this bug.  Apologies about the long wait.
