### ISSUE TITLE
Paste does not work with FireFox

### ISSUE THREAD

**Issue by MelchiorUU** [micrology/prsm#95]
I have copied a factor and tried to paste this. This leads to getting a "Failed to paste" error in the bottom of the screen.

When I try to paste the same element (clipboard data) in Edge it does work. 

I used Firefox 92.0 (64-bit) on Windows.

**Comment by micrology** [comment]
Unfortunately, Firefox has not (yet) implemented the necessary API for copy and paste, although Edge and Chrome have.  See comment on the implemenation of readText at https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
