### ISSUE TITLE
FR: Make undo button at the top also work for drawing mode/layer

### ISSUE THREAD

**Issue by MelchiorUU** [micrology/prsm#98]
Currently when I have drawn a line and press "undo" at the top it doesn't undo the drawn line.

It would be very nice and intuitive if the undo-button at the top would also undo. The undo button with the drawing tools is a bit unintuitive as users are used to have one central undo option.

**Comment by micrology** [comment]
Fixed by removing the undo button at the top, thus leaving only the one, operational, undo button
